### ISSUE TITLE
Update support for Livebook 0.14.2 

### ISSUE THREAD

**Issue by jshickey** [open-status/kino_curl#3]
I got the following error trying to kino_curl to the latest version of Livebook, thanks.

Resolving Hex dependencies...
Resolution completed in 0.024s
Because "the lock" specifies kino 0.14.2 and every version of kino_curl depends on kino ~> 0.8.0, the lock is incompatible with kino_curl.
And because your app depends on the lock, no version of kino_curl is allowed.
So, because your app depends on kino_curl ~> 0.1.0, version solving failed

**Comment by danielrudn** [comment]
Hey there, thanks for reporting this.

I've released version `0.2.0` of `kino_curl` which should resolve this issue.

If the issue still occurs, it may be due to another package requiring `kino` at `0.14.2`. If this is the case, you can add `{:kino, "~> 0.14.2", override: true}` to the list of dependencies to pull a specific version of Kino.

I also updated the readme to mention [Merquery](https://github.com/acalejos/merquery) since it's a great way to work with cURL commands in Livebook when using [Req](https://github.com/wojtekmach/req).

**Comment by jshickey** [comment]
Thanks!

Scott Hickey

Sent with [Proton Mail](https://proton.me/mail/home) secure email.
